dist: trusty
sudo: required
language: node_js
node_js: 10

install:
  - npm install -g purescript@0.12.0 pulp bower

script:
  - bin/fetch-configlet
  - bin/configlet --track-id purescript lint .
  - bin/check-bower.sh
  - LIMIT_CORES=1 bin/test.sh

cache:
  directories:
    - $HOME/.cache/bower/
